### ISSUE TITLE
luno.functional.all deve retornar "false" caso a lista seja vazia

### ISSUE THREAD

**Issue by GoogleCodeExporter** [echiesse/luno#3]
```
Hoje caso a lista seja vazia a função retorna "true"

```

Original issue reported on code.google.com by `echiesse` on 28 Nov 2014 at 10:51

**Comment by echiesse** [comment]
Comparado com o comportamento do Haskell (que é a base da implementação do Luno) e visto que retorna true com lista vazia então vou fechar esta  issue sem alterar o código.
